name: "CI/CD: Deploy Docker to Azure VM"

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy to Azure VM
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add server to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to VM
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            set -e  # Exit on any error
            cd ~/n8n/n8n-instance

            echo "Stopping and removing existing containers..."
            docker-compose down

            echo "Pulling latest image..."
            docker-compose pull

            echo "Starting new container..."
            docker-compose up -d
          EOF
