name: "CI/CD: Deploy Docker to Azure VM"

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy to Azure VM
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH private key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add server to known_hosts
        run: ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to Azure VM
        env:
          SSH_USER: ${{ secrets.SERVER_USER }}
          SSH_HOST: ${{ secrets.SERVER_IP }}
        run: |
          ssh ${SSH_USER}@${SSH_HOST} << 'EOF'
            set -e  # Stop on any error
            cd ~/n8n/n8n-instance

            echo "Pulling latest code from repo..."
            git pull

            echo "Shutting down existing containers..."
            docker-compose down

            echo "Pulling latest docker images..."
            docker-compose pull

            echo "Starting containers..."
            docker-compose up -d
          EOF
